### ISSUE TITLE
Crash version

### ISSUE THREAD

**Issue by brasilgameaction** [JC0NN0R/GASP-DynamicAdditiveOverlay#4]
This version is crashing when you asdd a new metahuman and afterwhen add Skeletal Mesh Asset in the body e after try to reset this field the game crash adn close

**Comment by JC0NN0R** [comment]
I'll look into this but I need to know specifically how you did it so that I can be sure that it's related to the project and not a bug in Unreal Engine. Unreal Engine does crash at times when you bring in characters and don't hook them up correctly. I will also need the Crash Report, you will have to download the editor symbols in order to provide a proper crash log, otherwise the crash message will just come out as random symbols.
![image](https://github.com/user-attachments/assets/9a4d5c68-343d-43ba-b8c5-cf8568bae9ca)

**Comment by brasilgameaction** [comment]
Ok I enable this option in my engine, thnak you.

**Comment by JC0NN0R** [comment]
Yeah I'm going to need more information then 'I add MetaHuman, Engine Crash'
That's so vague, and gives me absolutely nothing to work off.
